// US edition (ZeroDebtPlan) end-to-end checks.
const { openApp, ROOT } = require('./harness');
const path = require('path');
let pass = 0, fail = 0;
const ok = (c, name, extra) => { if (c) pass++; else { fail++; console.log('FAIL:', name, extra !== undefined ? JSON.stringify(extra) : ''); } };
const text = (page, id) => page.evaluate(id => (document.getElementById(id) || {}).textContent || '', id);
const go = (page, k) => page.evaluate(k => { App.go(k); if (k === 'config') document.querySelectorAll('[data-tab=config] details').forEach(d => { d.open = true; }); }, k);
(async () => {
  const { browser, page, errors } = await openApp({ file: 'index.html?edition=us', viewport: { width: 1366, height: 900 } });
  await page.evaluate(() => { Store.reset('starter'); App.commitHistory(); App.go('resumen'); });
  ok(await page.evaluate(() => [Store.KEY, Store.COUNTRY, document.title, I18n.lang].join()) === 'zerodebtplan_us_store,US,ZeroDebtPlan,en', 'US edition: own storage, country, title, English');
  ok((await text(page, 'brand-title')) === 'ZeroDebtPlan', 'brand name');
  const nav = await page.$$eval('#main-nav .nav-tab', els => els.map(e => e.textContent.replace(/\s+/g, ' ').trim()));
  ok(nav.length === 5 && nav.some(n => n.includes('Future')) && nav.some(n => n.includes('Transactions')) && nav.some(n => n.includes('Net Worth')), 'US navigation', nav);
  const futureTabs = await page.$$eval('[data-tab="futuro"] .tab-segmented button', els => els.map(e => e.textContent.trim()));
  ok(futureTabs.some(n => n.includes('Savings & CDs')) && futureTabs.some(n => n.includes('Mortgage')), 'Future holds savings, mortgage…', futureTabs);
  // Payroll
  await go(page, 'presupuesto/ingresos');
  const pay = await page.evaluate(() => App.buildContext().pay);
  ok(Math.abs(pay.netoM - 4007.56) < 0.01 && pay.country === 'US', 'Michigan single $5,000/mo → $4,007.56 net (2026 $5,900 exemption)', pay.netoM);
  ok((await text(page, 'inc-payroll')).includes('Federal income tax') && (await text(page, 'inc-payroll')).includes('Medicare') && (await text(page, 'inc-payroll')).includes('Michigan 4.25%'), 'payroll breakdown shows US taxes');
  ok(await page.isHidden('[data-bind="year.d3"]') && await page.isHidden('#inc-ded-status'), 'Ecuador-only fields are hidden');
  await page.selectOption('[data-bind="year.filingStatus"]', 'mfj');
  await page.fill('[data-bind="year.dependents"]', '2'); await page.dispatchEvent('[data-bind="year.dependents"]', 'input');
  ok(await page.evaluate(() => App.buildContext().pay.fedM) < pay.fedM && (await text(page, 'inc-us-ded-kpis')).includes('$4,400.00'), 'married + 2 kids: lower federal tax, $4,400 in credits');
  await page.selectOption('#inc-city', 'Detroit');
  ok(Math.abs(await page.evaluate(() => App.buildContext().pay.localM) - (5000 * 12 - 4 * 600) * 0.024 / 12) < 0.01 && (await text(page, 'inc-payroll')).includes('Detroit'), 'Detroit city tax 2.4% after $600 × 4 people');
  await page.selectOption('#inc-state', 'TX');
  ok(await page.evaluate(() => App.buildContext().pay.stateM) === 0 && (await text(page, 'inc-state-note')).includes("doesn't tax wages") && await page.evaluate(() => Store.active().localRate) === 0, 'Texas: no state tax, city reset');
  await page.selectOption('#inc-state', 'CA');
  ok((await text(page, 'inc-state-note')).includes("don't have California"), 'a state without a table asks for the rate');
  await page.fill('#inc-state-rate', '6'); await page.dispatchEvent('#inc-state-rate', 'change');
  ok(Math.abs(await page.evaluate(() => App.buildContext().pay.stateM) - 5000 * 0.06) < 0.01, 'typed state rate is used');
  await page.selectOption('#inc-state', 'MI');
  await page.selectOption('[data-bind="year.filingStatus"]', 'single');
  await page.fill('[data-bind="year.dependents"]', '0'); await page.dispatchEvent('[data-bind="year.dependents"]', 'input');
  await page.selectOption('#inc-city', '');
  // Pay stub: US taxes recognized as computed; 401(k) pre-tax lowers taxes
  await page.evaluate(() => PayScan.fromText(`Pay Period: 09/14/2026 - 09/27/2026  Pay Date: 10/02/2026\nGross Pay  2,307.69\nFederal Income Tax  170.00\nSocial Security  135.00\nMedicare  31.00\nMI State Income Tax  86.00\n401(k) Pre-Tax  138.46\nMedical PPO  69.23\nNet Pay  1,678.00`));
  await page.waitForSelector('#scan-save');
  const inc = await page.$$eval('.scan-inc', els => els.map(e => e.checked));
  ok(inc.filter(Boolean).length === 2 && (await page.textContent('.modal-backdrop:not(.hidden)')).includes('The app already calculates it'), 'stub: taxes are computed by the app; 401(k) and medical are kept', inc);
  ok(await page.inputValue('#scan-ppy') === '26', 'biweekly stub');
  const before = await page.evaluate(() => App.buildContext().pay.fedM);
  await page.click('#scan-save');
  const after = await page.evaluate(() => App.buildContext().pay);
  ok(after.fedM < before && after.pretaxM > 0 && Math.abs(after.otrosDescuentosM - (138.46 + 69.23) * 26 / 12) < 0.02, 'pre-tax deductions lower federal tax and come off net', [before, after.fedM, after.otrosDescuentosM]);
  await page.evaluate(() => { Store.active().payDeductions = []; App.changed({ structural: true }); });
  // Mortgage PITI
  await go(page, 'hipoteca');
  ok((await text(page, 'mort-summary')).includes('Total monthly payment (PITI)') && (await text(page, 'mort-summary')).includes('Principal & interest'), 'mortgage shows PITI');
  const piti = await page.evaluate(() => { const m = Store.state.mortgage; const pi = Engine.frenchPayment(m.amount, m.rate, m.years * 12); return Engine.pitiMonthly(Object.assign({ payment: pi }, m)).total; });
  ok(Math.abs(piti - (1580.17 + 4000 / 12 + 1500 / 12)) < 1, 'PITI = P&I + tax + insurance', piti);
  // Retirement: Social Security
  await go(page, 'jubilacion');
  const ss = await page.evaluate(() => App.buildContext().retirement.pension);
  ok(ss > 1500 && ss < 3000 && (await page.textContent('[data-view="jubilacion"]')).includes('Social Security'), 'retirement uses a Social Security estimate', ss);
  ok(await page.isHidden('[data-bind="retirement.tasaReemplazo"]'), 'IESS replacement rate hidden');
  // Import: OFX
  await go(page, 'presupuesto/importar');
  ok(await page.isHidden('#imp-xml'), 'SRI invoice import hidden');
  const n0 = await page.evaluate(() => Store.state.transactions.length);
  await page.setInputFiles('#imp-file', path.join(ROOT, 'tests/fixtures/chase.ofx'));
  await page.waitForTimeout(250);
  ok((await page.textContent('#imp-summary')).includes('3 to import'), 'OFX rows read', await page.textContent('#imp-summary'));
  await page.selectOption('#imp-ofx-account select', 'new:ahorros');
  await page.click('#imp-commit');
  const acct = await page.evaluate(() => Store.state.accounts[Store.state.accounts.length - 1]);
  ok(await page.evaluate(() => Store.state.transactions.length) === n0 + 3 && acct && acct.balance === 2340.55, 'OFX imported and the account balance updated', acct);
  await page.setInputFiles('#imp-file', path.join(ROOT, 'tests/fixtures/chase.ofx'));
  await page.waitForTimeout(250);
  ok((await page.textContent('#imp-summary')).includes('0 to import'), 'the same OFX again: all already imported (FITID)', await page.textContent('#imp-summary'));
  await page.click('[data-action="imp.cancel"]');
  // Settings: US tax table, FDIC
  await go(page, 'config');
  ok(await page.$$eval('#cfg-us-brackets tr', r => r.length) === 7 && await page.isHidden('[data-bind="year.iessRate"]'), 'federal table editable; IESS parameters hidden');
  await page.fill('[data-bind="year.usTax.stdDeduction.single"]', '20000'); await page.dispatchEvent('[data-bind="year.usTax.stdDeduction.single"]', 'input');
  ok(await page.evaluate(() => App.buildContext().pay.stdDeduction) === 20000, 'nested tax parameters are editable');
  // Spanish in the US edition: US wording
  await page.selectOption('#cfg-lang', 'es');
  await page.waitForTimeout(150);
  const navEs = await page.$$eval('#main-nav .nav-tab', els => els.map(e => e.textContent.replace(/\s+/g, ' ').trim()));
  const futEs = await page.$$eval('[data-tab="futuro"] .tab-segmented button', els => els.map(e => e.textContent.trim()));
  ok(futEs.some(n => n.includes('Ahorro y CDs')) && navEs.some(n => n.includes('Resumen')), 'Spanish in the US edition uses US wording', navEs.concat(futEs));
  await go(page, 'jubilacion');
  ok((await page.textContent('[data-view="jubilacion"]')).includes('Seguro Social') && !(await page.textContent('[data-view="jubilacion"]')).includes('Pensión IESS'), 'Spanish: Seguro Social, not IESS');
  await page.selectOption('#cfg-lang', 'en').catch(async () => { await go(page, 'config'); await page.selectOption('#cfg-lang', 'en'); });
  // Mobile
  await page.setViewportSize({ width: 390, height: 844 });
  for (const k of ['resumen', 'presupuesto/ingresos', 'hipoteca', 'config']) {
    await go(page, k); await page.waitForTimeout(200);
    ok(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth) <= 0, `US: no horizontal scroll on mobile (${k})`);
  }
  // Next moves on the Overview (example family): three, snoozing one brings the next.
  await page.evaluate(() => { Store.reset('example'); App.changed({ structural: true }); App.go('resumen'); });
  await page.waitForTimeout(200);
  const mv0 = await page.$$eval('#dash-moves .move-title', a => a.map(e => e.textContent.trim()));
  ok(mv0.length === 3 && await page.isVisible('#dash-moves-card'), 'Overview shows the next 3 moves', mv0);
  const health = await page.evaluate(() => ({ n: Number(document.querySelector('#dash-health .health-num').textContent), pillars: document.querySelectorAll('#dash-health .health-pillar').length, txt: document.getElementById('dash-health').textContent }));
  ok(health.n >= 0 && health.n <= 100 && health.pillars === 4 && /Spend/.test(health.txt) && /Borrow/.test(health.txt), 'Overview shows the financial health score with 4 pillars', health.n);
  const firstKey = await page.$eval('#dash-moves [data-action="moves.snooze"]', b => b.dataset.key);
  await page.click('#dash-moves [data-action="moves.snooze"]');
  const mv1 = await page.$$eval('#dash-moves [data-action="moves.snooze"]', a => a.map(e => e.dataset.key));
  ok(!mv1.includes(firstKey) && await page.evaluate(k => !!Store.state.settings.movesSnoozed[k], firstKey), 'Not now hides a move for two weeks', [firstKey, mv1]);
  // Retirement: need vs. have, and the monthly fix goes into the simulator.
  await go(page, 'futuro/jubilacion');
  await page.waitForTimeout(200);
  ok(/You'd need/.test(await page.textContent('#ret-gap')) && /%/.test(await page.textContent('#ret-gap')), 'retirement shows need vs have', (await page.textContent('#ret-gap')).slice(0, 120));
  await page.fill('#ret-desired', '20000');
  await page.dispatchEvent('#ret-desired', 'input');
  await page.waitForTimeout(150);
  ok(/more a month/.test(await page.textContent('#ret-gap')), 'a bigger lifestyle shows the extra monthly saving');
  await page.click('#ret-gap [data-action="ret.tryGap"]');
  ok(await page.evaluate(() => Store.state.retirement.whatIfExtra > 0), 'the fix goes into the what-if simulator');
  // Budget coaching (example family).
  await page.evaluate(() => { App.go('presupuesto/plan'); document.getElementById('bud-coach-card').open = true; });
  await page.waitForTimeout(200);
  const coachTxt = await page.textContent('#bud-coach');
  ok(/Housing/.test(coachTxt) && /guideline|Guideline/.test(coachTxt) && await page.$$eval('#bud-coach tbody tr', r => r.length) >= 5, 'budget coaching compares the plan with guidelines', coachTxt.slice(0, 120));
  // Insurance check (example family): guessed from the budget, answers override.
  await page.evaluate(() => { App.go('futuro/metas'); document.getElementById('metas-insurance').open = true; });
  await page.waitForTimeout(200);
  const ins = await page.$$eval('#ins-list .ins-row', r => r.map(e => e.className.split(' ').pop()));
  ok(ins.length === 7 && ins.includes('ok'), 'insurance check lists 7 coverages with what you have', ins);
  const missingBefore = await page.evaluate(() => document.querySelectorAll('#ins-list .ins-row.falta').length);
  if (missingBefore) {
    const key = await page.$eval('#ins-list .ins-row.falta select', s => s.dataset.key);
    await page.selectOption(`#ins-list select[data-key="${key}"]`, 'si');
    ok(await page.evaluate(() => document.querySelectorAll('#ins-list .ins-row.falta').length) === missingBefore - 1, 'saying you have it marks it covered');
  }
  // College estimator (example family): Emma linked to her 529 goal, a goal created for Leo.
  await page.evaluate(() => { Store.reset('example'); App.changed({ structural: true }); App.go('futuro/metas'); document.getElementById('metas-college').open = true; });
  await page.waitForTimeout(200);
  ok(await page.$$eval('#college-results .college-card', c => c.length) === 2 && /Total cost/.test(await page.textContent('#college-results')), 'college estimator shows each child');
  const nGoals = await page.evaluate(() => Store.state.goals.length);
  await page.click('#college-results [data-action="college.goal"]');
  const leo = await page.evaluate(() => { const k = Store.state.college.kids.find(x => x.name === 'Leo'); const g = Store.state.goals.find(x => x.id === k.goalId); return g && { name: g.name, monthly: g.monthly, target: g.target, n: Store.state.goals.length }; });
  ok(leo && leo.n === nGoals + 1 && /Leo/.test(leo.name) && leo.monthly > 0 && leo.target > 100000, 'a savings goal is created and linked for the child', leo);
  // Estate + yearly review checklists keep the date of each step.
  await go(page, 'patrimonio');
  await page.waitForTimeout(150);
  ok(await page.$$eval('#check-estate .check-item', a => a.length) === 6 && await page.$$eval('#check-review .check-item', a => a.length) === 9, 'estate and yearly review checklists');
  await page.click('#check-estate input[data-key="will"]');
  await page.click('#check-review input[data-key="credit"]');
  const ck = await page.evaluate(() => ({ will: Store.state.checklists.estate.will, credit: (Store.state.checklists.review[String(new Date().getFullYear())] || {}).credit, pct: document.getElementById('check-estate-pct').textContent, today: Engine.isoDate(new Date()) }));
  ok(ck.will === ck.today && ck.credit === ck.today && ck.pct === '17%', 'checking a step saves its date (the yearly one under this year)', ck);
  // Chart values show under the chart, not in a box over it (plan phone-and-corebank, step 2).
  await page.evaluate(() => { Store.reset('example'); App.changed({ structural: true }); App.go('resumen'); });
  await page.waitForTimeout(400);
  const cv = await page.$('#dash-curve-chart');
  await cv.scrollIntoViewIfNeeded();
  const bb = await cv.boundingBox();
  await page.mouse.move(bb.x + bb.width * 0.6, bb.y + bb.height * 0.5);
  await page.waitForTimeout(300);
  const ro = await page.evaluate(() => { const c = UI.chartInstance('dash-curve-chart'), r = c.canvas.parentNode.nextElementSibling; return { cls: r && r.className, txt: r && r.textContent, box: c.options.plugins.tooltip.enabled }; });
  ok(ro.cls === 'chart-readout' && /\$/.test(ro.txt || '') && ro.box === false, 'tapping a chart shows its values under the chart (no box over it)', ro);
  // Edit an automatic rule (step 3).
  await page.evaluate(() => { Store.state.rules = [{ id: 7, contains: 'STARBUKS', category: 'Alimentación', sub: 'Mercado/Supermercado' }]; App.changed({ structural: true }); App.go('transacciones/importar'); });
  await page.waitForTimeout(250);
  await page.click('[data-action="rule.edit"][data-id="7"]');
  await page.waitForSelector('.modal-backdrop:not(.hidden) [data-dialog-ok]');
  const preset = await page.evaluate(() => document.querySelector('.modal select[name="cat"]').value);
  await page.fill('.modal input[name="contains"]', 'STARBUCKS');
  await page.fill('.modal input[name="rename"]', 'Starbucks');
  await page.selectOption('.modal select[name="cat"]', 'G|Alimentación|Restaurantes');
  await page.click('[data-dialog-ok]');
  await page.waitForTimeout(250);
  const ru = await page.evaluate(() => ({ r: Store.state.rules[0], row: document.getElementById('rule-body').textContent }));
  ok(preset === 'G|Alimentación|Mercado/Supermercado' && ru.r.contains === 'STARBUCKS' && ru.r.rename === 'Starbucks' && ru.r.sub === 'Restaurantes' && ru.r.type === 'Gasto' && /STARBUCKS/.test(ru.row), 'a rule can be edited: text, name, category and subcategory', ru);
  // Categories live in Settings: rename (carried to transactions) and add a subcategory (step 4).
  await page.evaluate(() => { Store.reset('example'); App.changed({ structural: true }); App.go('config'); document.getElementById('cfg-categories').open = true; });
  await page.waitForTimeout(250);
  const catBefore = await page.evaluate(() => Store.state.transactions.filter(t => t.parentCategory === 'Alimentación').length);
  await page.click('[data-action="cat.rename"][data-parent="Alimentación"]');
  await page.waitForSelector('.modal-backdrop:not(.hidden) [data-dialog-ok]');
  const shown = await page.inputValue('.modal input[name="name"]');
  await page.fill('.modal input[name="name"]', 'Groceries & Dining');
  await page.click('[data-dialog-ok]');
  await page.waitForTimeout(250);
  await page.click('[data-action="cat.addSub"][data-parent="Groceries & Dining"]');
  await page.waitForSelector('.modal-backdrop:not(.hidden) [data-dialog-ok]');
  await page.fill('.modal input[name="name"]', 'Coffee');
  await page.click('[data-dialog-ok]');
  await page.waitForTimeout(250);
  const cr = await page.evaluate(() => ({ n: Store.state.transactions.filter(t => t.parentCategory === 'Groceries & Dining').length, old: Store.state.transactions.filter(t => t.parentCategory === 'Alimentación').length, subs: Store.state.taxonomy.expense['Groceries & Dining'], list: document.getElementById('cat-list').textContent }));
  ok(shown === 'Food' && catBefore > 0 && cr.n === catBefore && cr.old === 0 && cr.subs.includes('Coffee') && /Groceries & Dining/.test(cr.list), 'Settings → Categories: rename carries to transactions; add a subcategory', [shown, catBefore, cr.n, cr.old]);
  // Household (shared) next to each person (step 5).
  await page.evaluate(() => { Store.reset('example'); if (!(Store.state.members || []).length) Store.state.members = [{ id: 1, name: 'Ana', color: '#2a78d6' }]; App.changed({ structural: true }); App.go('transacciones/lista'); });
  await page.waitForTimeout(250);
  const hh = await page.evaluate(() => {
    const opts = [...document.querySelectorAll('#txn-member option')].map(o => [o.value, o.textContent]);
    const ym = Engine.isoDate(new Date()).slice(0, 7), t = Store.state.transactions.find(x => (x.type || 'Gasto') === 'Gasto' && x.date.startsWith(ym)) || Store.state.transactions.find(x => (x.type || 'Gasto') === 'Gasto');
    t.memberId = Engine.HOUSEHOLD;
    App.changed({ structural: true });
    return { opts, badge: !!document.querySelector('.member-dot[title="Household (shared)"]') };
  });
  ok(hh.opts.some(([v, l]) => v === '-1' && /Household \(shared\)/.test(l)) && hh.opts[0][0] === '', 'Whose? offers "Household (shared)" next to each person', hh.opts);
  await page.evaluate(() => { App.go('transacciones/reportes'); });
  await page.waitForTimeout(200);
  await page.selectOption('#rep-by', 'member');
  await page.waitForTimeout(200);
  ok(/Household/.test(await page.textContent('#rep-body')), 'reports by person show the household as its own row');
  // Typed vs. imported; typed ones not on a statement yet (step 8).
  await page.evaluate(() => { const d = Engine.isoDate(new Date()); Store.reset('empty'); Store.state.transactions = [
    { id: 1, type: 'Gasto', description: 'Typed coffee', parentCategory: 'Alimentación', category: 'Restaurantes', amount: 4, date: d, createdAt: d },
    { id: 2, type: 'Gasto', description: 'Typed and matched', parentCategory: 'Alimentación', category: 'Restaurantes', amount: 9, date: d, importRef: 'r1' },
    { id: 3, type: 'Gasto', description: 'From the bank', parentCategory: 'Alimentación', category: 'Restaurantes', amount: 12, date: d, source: 'csv', importRef: 'r2' }];
    App.changed({ structural: true }); App.go('transacciones/lista'); });
  await page.waitForTimeout(250);
  await page.selectOption('#txn-f-origin', 'unreconciled');
  await page.waitForTimeout(200);
  const rec = await page.evaluate(() => ({ list: document.getElementById('txn-body').textContent }));
  ok(/Typed coffee/.test(rec.list) && !/Typed and matched/.test(rec.list) && !/From the bank/.test(rec.list) && /Typed/.test(rec.list), 'filter: typed transactions no statement has confirmed yet', rec.list.slice(0, 200));
  await page.selectOption('#txn-f-origin', 'all');
  await page.waitForTimeout(200);
  const all = await page.evaluate(() => document.getElementById('txn-body').textContent);
  ok(/confirmed by a statement/.test(all) && /Imported/.test(all), 'each transaction says where it came from', all.slice(0, 300));
  // Hourly pay, overtime and bonuses (docs/plans/hourly-pay.md, phase 2).
  await page.evaluate(() => { Store.reset('example'); Store.active().sueldo = 5000; Store.active().payDeductions = []; App.changed({ structural: true }); App.go('presupuesto/ingresos'); });
  await page.waitForTimeout(200);
  const net0 = await page.evaluate(() => Engine.payroll(Store.effective(Store.state.activeYear)).netoM);
  await page.selectOption('#inc-paytype [data-change="paytype.set"]', 'hourly');
  await page.waitForTimeout(200);
  const hr = await page.evaluate(() => ({ t: Store.active().payType, rate: Store.active().hourly.rate, sueldo: Store.active().sueldo, ro: document.getElementById('inc-sueldo').readOnly, label: document.getElementById('inc-sueldo-label').textContent }));
  ok(hr.t === 'hourly' && Math.abs(hr.rate - 28.85) < 0.01 && Math.abs(hr.sueldo - 5000) < 2 && hr.ro && /base pay/.test(hr.label), 'switching to hourly starts from the salary (same base pay); the monthly field is worked out', hr);
  const setHourly = async (field, v) => { await page.fill(`#inc-paytype input[data-field="${field}"]`, String(v)); await page.dispatchEvent(`#inc-paytype input[data-field="${field}"]`, 'change'); await page.waitForTimeout(150); };
  await setHourly('rate', 25); await setHourly('hours', 40); await setHourly('otHours', 5);
  const h1 = await page.evaluate(() => ({ sueldo: Store.active().sueldo, net: Engine.payroll(Store.effective(Store.state.activeYear)).netoM, txt: document.getElementById('inc-paytype').textContent.replace(/\s+/g, ' '), annual: document.getElementById('inc-annual').textContent }));
  ok(Math.abs(h1.sueldo - 4333.33) < 0.01 && /Base pay: \$4,333\.33 a month/.test(h1.txt) && /Usual overtime: \$812\.50 a month/.test(h1.txt) && /\$61,750\.00/.test(h1.annual), '$25 × 40 h: base $4,333.33; overtime $812.50; the year $61,750', h1);
  await page.check('#inc-paytype input[data-field="otInBudget"]');
  await page.waitForTimeout(150);
  const h2 = await page.evaluate(() => Engine.payroll(Store.effective(Store.state.activeYear)).netoM);
  ok(h2 > h1.net + 500, 'counting overtime raises the budget\'s take-home pay', [h1.net, h2]);
  await page.click('#inc-paytype [data-action="bonus.add"]');
  await page.waitForTimeout(150);
  await page.fill('#inc-paytype input[data-field="amount"]', '3000');
  await page.dispatchEvent('#inc-paytype input[data-field="amount"]', 'change');
  await page.waitForTimeout(150);
  await page.check('#inc-paytype input[data-field="inBudget"]');
  await page.waitForTimeout(150);
  const bn = await page.evaluate(() => { const yd = Store.effective(Store.state.activeYear), p = Engine.payroll(yd); return { b: Store.active().bonuses[0], dec: Engine.monthBudget(yd, '12', p).salary - Engine.monthBudget(yd, '11', p).salary }; });
  ok(bn.b.amount === 3000 && bn.b.month === '12' && bn.b.inBudget && bn.dec > 2000 && bn.dec < 3000, 'a planned $3,000 December bonus adds its take-home to December', bn);
  await page.evaluate(() => { Device.setLang('es'); });
  await page.waitForTimeout(250);
  const esTxt = (await page.textContent('#inc-paytype')).replace(/\s+/g, ' ');
  ok(/Cómo te pagan/.test(esTxt) && /Bonos este año/.test(esTxt) && /Pago por hora/.test(esTxt) && /Diciembre/.test(esTxt), 'the pay block in Spanish', esTxt.slice(0, 160));
  await page.evaluate(() => { Device.setLang('en'); });
  await page.waitForTimeout(150);
  await page.selectOption('#inc-paytype [data-change="paytype.set"]', 'salary');
  await page.waitForTimeout(150);
  ok(await page.evaluate(() => Store.active().payType === 'salary' && !document.getElementById('inc-sueldo').readOnly), 'back to salary: the monthly field is typed again');
  ok(net0 > 0, 'baseline take-home', net0);
  // Pay stub with hours, overtime and a bonus (phase 4): back to a salary first, then scan.
  await page.evaluate(() => { const y = Store.active(); y.payType = 'salary'; y.bonuses = []; App.changed({ structural: true }); PayScan.fromText('Pay Period: 09/14/2026 - 09/27/2026  Pay Date: 10/02/2026\nEarnings Rate Hours Current YTD\nRegular 25.0000 80.00 2,000.00 38,000.00\nOvertime 37.5000 6.00 225.00 1,125.00\nBonus 500.00 500.00\nGross Pay 2,725.00\nFederal Income Tax 250.00\nNet Pay 2,100.00'); });
  await page.waitForTimeout(250);
  const sc = (await page.textContent('.sheet-body')).replace(/\s+/g, ' ');
  ok(/Paid by the hour: \$25\.00 an hour, 40 hours a week/.test(sc) && /3 hours a week at 1\.5×/.test(sc) && /Add this \$500\.00 bonus/.test(sc), 'the stub review offers its hourly pay, overtime and bonus', sc.slice(0, 300));
  await page.check('#scan-ot');
  await page.waitForTimeout(150);
  await page.click('#scan-save');
  await page.waitForTimeout(250);
  const st = await page.evaluate(() => { const y = Store.active(); return { t: y.payType, h: y.hourly, sueldo: y.sueldo, b: y.bonuses.map(b => [b.amount, b.month, b.inBudget]) }; });
  ok(st.t === 'hourly' && st.h.rate === 25 && st.h.hours === 40 && st.h.otHours === 3 && st.h.otRate === 1.5 && Math.abs(st.sueldo - 4333.33) < 0.01 && JSON.stringify(st.b) === '[[500,"10",false]]', 'saving the stub sets hourly pay, usual overtime and the paid bonus', st);
  // Extra paychecks (phase 3): every 2 weeks from the year's first Friday.
  await page.evaluate(() => { const y = Store.state.activeYear, d = new Date(y, 0, 1); d.setDate(1 + (5 - d.getDay() + 7) % 7); Store.state.settings.paySchedule = { freq: 'weekly', weekday: 5, interval: 2, anchor: Engine.isoDate(d) }; App.changed({ structural: true }); });
  await page.waitForTimeout(200);
  const xp = await page.evaluate(() => ({ txt: document.getElementById('pay-extra').textContent.replace(/\s+/g, ' '), months: Engine.extraPaycheckMonths(Store.state.settings.paySchedule, Store.state.activeYear).months.map(m => Fmt.MONTH_NAMES[m.month - 1]) }));
  ok(xp.months.length >= 2 && /3rd paycheck in/.test(xp.txt) && xp.months.every(m => xp.txt.includes(m)) && /Budget on 2 paychecks a month/.test(xp.txt), 'every 2 weeks: the months with a 3rd paycheck are named', xp);
  await page.check('#pay-extra input[data-change="pay.onChecks"]');
  await page.waitForTimeout(200);
  const oc = await page.evaluate(() => { const yd = Store.effective(Store.state.activeYear), p = Engine.payroll(yd), m = Engine.extraPaycheckMonths(yd.paySchedule, yd.calYear).months[0].month; return { on: Store.active().budgetOnPaychecks, base: Engine.monthBudget(yd, 'base', p).salary, extra: Engine.monthBudget(yd, String(m), p).salary, each: p.netoM * 12 / 26, toast: [...document.querySelectorAll('.toast')].map(t => t.textContent).join('|') }; });
  ok(oc.on && Math.abs(oc.base - oc.each * 2) < 0.01 && Math.abs(oc.extra - oc.each * 3) < 0.01 && /Budgeting on your paychecks/.test(oc.toast), 'budget on 2 paychecks: the plan has 2, the extra month 3', oc);
  // Refund or owe (example family): a refund now; less withholding → owe, with the W-4 fix.
  await page.evaluate(() => { Store.reset('example'); App.changed({ structural: true }); App.go('presupuesto/ingresos'); });
  await page.waitForTimeout(200);
  ok(/Your refund would be/.test(await page.textContent('#inc-refund')), 'the example family gets a refund estimate', (await page.textContent('#inc-refund')).slice(0, 120));
  await page.fill('#inc-refund-in [data-key="perCheck"]', '40');
  await page.dispatchEvent('#inc-refund-in [data-key="perCheck"]', 'input');
  await page.waitForTimeout(150);
  const owe = await page.textContent('#inc-refund');
  ok(/You'd owe/.test(owe) && /more per paycheck/.test(owe) && await page.evaluate(() => document.activeElement && document.activeElement.dataset.key === 'perCheck'), 'less withholding → owe, with extra per paycheck; typing keeps focus', owe.slice(0, 160));
  // Itemize or standard: the example family is better off with the standard deduction; a bigger
  // mortgage interest flips it, and "Use" puts the itemized total in the paycheck math.
  await page.evaluate(() => { Store.reset('example'); App.changed({ structural: true }); App.go('presupuesto/ingresos'); });
  await page.waitForTimeout(200);
  const it0 = (await page.textContent('#inc-itemize')).replace(/\s+/g, ' ');
  ok(/Mortgage interest/.test(it0) && /State, local and property taxes/.test(it0) && /Charitable gifts/.test(it0) && /The standard deduction is better for you/.test(it0) && /\$34,200/.test(it0), 'itemize check: the example family takes the standard deduction (+ $2,000 for gifts)', it0.slice(0, 300));
  await page.fill('#inc-itemize-in [data-key="mortgage"]', '30000');
  await page.dispatchEvent('#inc-itemize-in [data-key="mortgage"]', 'input');
  await page.waitForTimeout(150);
  const it1 = await page.textContent('#inc-itemize');
  ok(/Itemizing is better for you/.test(it1) && await page.evaluate(() => document.activeElement && document.activeElement.dataset.key === 'mortgage'), 'more mortgage interest → itemize, and typing keeps focus', it1.slice(0, 200));
  const fed0 = await page.evaluate(() => App.buildContext().pay.fedM);
  await page.click('#inc-itemize [data-action="itemize.use"]');
  await page.waitForTimeout(150);
  ok(await page.evaluate(() => Store.active().itemized) > 32200 && await page.evaluate(() => App.buildContext().pay.fedM) < fed0 && /Itemized/.test(await page.textContent('#inc-us-ded-kpis')), '"Use" sets the itemized deduction and lowers the federal tax');
  // Investments: cost and gain per holding, the mix against the target, rebalancing, new money.
  await page.evaluate(() => { Store.reset('example'); App.changed({ structural: true }); App.go('patrimonio'); });
  await page.waitForTimeout(200);
  const hold = (await page.textContent('#nw-holdings')).replace(/\s+/g, ' ');
  ok(/\+\$1,522 \(\+24\.9%\)/.test(hold) && /\+\$2,240 \(\+19\.0%\)/.test(hold) && /Manual/.test(hold), 'gain per holding and in total', hold.slice(0, 200));
  ok(/drifted 5\.6 points/.test(hold) && /Buy \$788/.test(hold) && /Sell \$663/.test(hold), 'the example mix has drifted: buy and sell amounts', hold.match(/U\.S\. stocks\$.{0,200}/));
  await page.fill('#mix-new', '1000');
  await page.dispatchEvent('#mix-new', 'input');
  await page.waitForTimeout(100);
  const split = await page.textContent('#mix-split');
  ok(/U\.S\. stocks\s*\$888\s*International stocks\s*\$112/.test(split), 'new money only: where to put the next contribution', split);
  ok(await page.evaluate(() => document.activeElement && document.activeElement.id === 'mix-new'), 'typing the contribution keeps focus');
  await page.click('[data-action="mix.preset"][data-key="calm"]');
  await page.waitForTimeout(150);
  ok(await page.evaluate(() => Store.state.investTarget.bonds === 40 && document.querySelector('#mix-in [data-key="bonds"]').value === '40'), 'a preset sets the target and the inputs show it');
  await page.selectOption('#mix-in select[data-id="3"]', 'cash');
  await page.waitForTimeout(100);
  ok(await page.evaluate(() => Store.state.holdings.find(h => h.id === 3).asset === 'cash') && /Cash \/ money market/.test(await page.textContent('#mix-bars')), 'a holding\'s class can be changed');
  const costCell = '#hold-body tr[data-row="1"] [data-field="cost"]';
  await page.fill(costCell, '9000'); await page.dispatchEvent(costCell, 'input');
  await page.waitForTimeout(100);
  ok(/−\$1,358/.test(await page.textContent('#hold-body tr[data-row="1"] [data-cell="gain"]')), 'a higher cost shows a loss');
  // Prepay the mortgage or invest: the example at 10% → investing wins, with the break-even; at 5% → prepay.
  await page.evaluate(() => { Store.reset('example'); App.changed({ structural: true }); App.go('futuro/hipoteca'); });
  await page.waitForTimeout(200);
  const pp = (await page.textContent('#mort-prepay')).replace(/\s+/g, ' ');
  ok(/investing would leave \$[\d,]+ more/.test(pp) && /only wins if it earns more than 6\.\d% a year/.test(pp) && /House paid off \d+y/.test(pp) && /From your balance today/.test(pp), 'prepay or invest: investing wins at 10%, with the break-even', pp.slice(0, 300));
  await page.fill('#mort-prepay-in [data-key="returnPct"]', '5');
  await page.dispatchEvent('#mort-prepay-in [data-key="returnPct"]', 'input');
  await page.waitForTimeout(100);
  ok(/Paying down the house leaves \$[\d,]+ more/.test(await page.textContent('#mort-prepay-out')) && await page.evaluate(() => document.activeElement.dataset.key === 'returnPct'), 'at 5% paying the house wins; typing keeps focus');
  // Rate sensitivity: the mortgage at ±1 point, CDs renewing 1 point lower.
  await page.evaluate(() => { Store.reset('example'); App.changed({ structural: true }); App.go('futuro/hipoteca'); });
  await page.waitForTimeout(200);
  const rates = (await page.textContent('#mort-rates')).replace(/\s+/g, ' ');
  ok(/1 point lower · 5\.25% \$1,501\.99/.test(rates) && /1 point higher · 7\.25% \$1,855\.52/.test(rates) && /\+\$181\/mo/.test(rates), 'mortgage payment and interest at ±1 point', rates.slice(0, 200));
  await go(page, 'ahorro/polizas');
  await page.waitForTimeout(150);
  ok(/If the rate is 1 point lower when they renew, they'd earn \$[\d,]+: \$[\d,]+ less a year/.test(await page.textContent('#pol-rate-risk')), 'CDs: what a 1-point lower renewal costs a year');
  // Side income: the example's photography income → % to set aside, a tax fund goal.
  await page.evaluate(() => { Store.reset('example'); App.changed({ structural: true }); App.go('presupuesto/ingresos'); });
  await page.waitForTimeout(200);
  const side = await page.textContent('#inc-side');
  const sidePct = Number((side.match(/(\d+)%/) || [])[1]);
  ok(/Side income/.test(side) && sidePct >= 20 && sidePct <= 45 && /quarterly/.test(side), 'side income shows the share to set aside and quarterly payments', side.slice(0, 160));
  await page.click('#inc-side [data-action="side.goal"]');
  ok(await page.evaluate(() => Store.state.goals.some(g => g.taxFund && g.monthly > 0)), 'a tax fund goal can be created');
  // Subscription finder on the example family.
  await page.evaluate(() => { Store.reset('example'); App.changed({ structural: true }); App.go('transacciones/lista'); });
  await page.waitForTimeout(200);
  const foundTxt = await page.textContent('#rec-found');
  ok(/Disney\+/.test(foundTxt) && /iCloud/.test(foundTxt) && /repeating charge/.test(foundTxt), 'the finder lists untracked subscriptions', foundTxt.slice(0, 200));
  const nRec = await page.evaluate(() => Store.state.recurring.length);
  await page.click('#rec-found .found-row:has-text("Disney+") [data-action="subs.track"]');
  const tracked = await page.evaluate(() => { const r = Store.state.recurring.find(x => x.description === 'Disney+'); return r && { r, linked: Store.state.transactions.filter(t => t.recurringId === r.id).length, n: Store.state.recurring.length, next: Engine.nextOccurrence(r, new Date()), today: Engine.isoDate(new Date()) }; });
  ok(tracked && tracked.n === nRec + 1 && tracked.r.frequency === 'monthly' && tracked.linked >= 12 && tracked.next >= tracked.today, 'Schedule turns it into a repeating movement linked to its past charges', tracked && [tracked.n, tracked.linked, tracked.next]);
  ok(!/Disney\+/.test(await page.textContent('#rec-found')), 'a scheduled one leaves the list');
  ok(await page.evaluate(() => Engine.dueOccurrences(Store.state.recurring.find(x => x.description === 'Disney+'), new Date()).length === 0), 'scheduling does not re-post charges already logged');
  await page.click('#rec-found .found-row:has-text("Help for Mom") [data-action="subs.dismiss"]');
  ok(!/Help for Mom/.test(await page.textContent('#rec-found')) && await page.evaluate(() => (Store.state.settings.dismissedRepeats || []).length === 1), 'Not recurring hides it for good');
  // Net worth month by month + milestones (example family).
  await go(page, 'patrimonio');
  await page.waitForTimeout(200);
  const prog = await page.evaluate(() => ({ points: (UI.chartInstance('nw-month-chart') || { data: { datasets: [{ data: [] }] } }).data.datasets[0].data.length, txt: document.getElementById('nw-milestones').textContent, hist: Store.state.netWorthHistory.length }));
  ok(prog.points === Math.min(12, prog.hist) && prog.hist >= 12, 'the example shows net worth month by month', prog.points);
  ok(/Reached \(\d+\)/.test(prog.txt) && /Up next/.test(prog.txt) && /Net worth of \$/.test(prog.txt), 'milestones: reached and up next', prog.txt.slice(0, 160));
  const er = await page.evaluate(() => Store.state.debts.find(d => /ER bill/.test(d.name)));
  await go(page, 'futuro/metas');
  await page.click(`#debt-body tr[data-row="${er.id}"] [data-action="debt.pay"]`);
  await page.fill('.modal input[name="amount"]', String(er.balance));
  await page.fill('.modal input[name="interest"]', '0');
  await page.click('[data-dialog-ok]');
  await page.waitForTimeout(600);
  const ms = await page.evaluate(id => ({ m: Store.state.milestones['debt-' + id], toasts: [...document.querySelectorAll('.toast')].map(t => t.textContent).join(' | ') }), er.id);
  ok(ms.m === await page.evaluate(() => Engine.isoDate(new Date())) && /Milestone!/.test(ms.toasts), 'paying a debt off is a dated, celebrated milestone', ms);
  // Phones: debts and goals show as one card per row, each field labeled; tables on desktop.
  await page.setViewportSize({ width: 1366, height: 900 });
  await page.evaluate(() => { Store.reset('example'); App.changed({ structural: true }); App.go('futuro/metas'); });
  await page.waitForTimeout(150);
  ok(await page.isVisible('#metas-goals thead') && await page.evaluate(() => getComputedStyle(document.querySelector('#debt-body tr')).display) === 'table-row', 'desktop: debts and goals stay tables', await page.evaluate(() => [getComputedStyle(document.querySelector('#metas-goals thead')).display, getComputedStyle(document.querySelector('#debt-body tr')).display, innerWidth, Store.ui.tab, document.querySelectorAll('#debt-body tr').length]));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(200);
  const card = await page.evaluate(() => ({ head: getComputedStyle(document.querySelector('#metas-goals thead')).display, row: getComputedStyle(document.querySelector('#debt-body tr')).display,
    labels: [...document.querySelectorAll('#goal-body tr:first-child td')].map(td => getComputedStyle(td, '::before').content), over: document.documentElement.scrollWidth - innerWidth }));
  ok(card.head === 'none' && card.row === 'grid' && card.labels.includes('"Budget per month"') && card.labels.includes('"Target"') && card.over <= 0, 'phone: debts and goals as labeled cards, no sideways scroll', card);
  await page.fill('#debt-body tr:first-child [data-field="balance"]', '1234');
  await page.dispatchEvent('#debt-body tr:first-child [data-field="balance"]', 'input');
  ok(await page.evaluate(() => Store.state.debts[0].balance === 1234 && document.activeElement.dataset.field === 'balance'), 'phone: editing in a card works and keeps focus');
  await page.setViewportSize({ width: 1366, height: 900 });
  // Erase all my data in English: the dialog asks for DELETE, any case works, then a box confirms.
  await page.evaluate(() => { Store.reset('example'); App.changed({ structural: true }); App.go('config'); document.querySelectorAll('[data-tab=config] details').forEach(d => { d.open = true; }); });
  await page.click('[data-action="cfg.purge"]');
  await page.waitForTimeout(100);
  ok(/Type DELETE to confirm/.test(await page.textContent('.modal')), 'English: the erase dialog asks for DELETE');
  await page.fill('.modal input[name="word"]', 'Delete');
  await page.click('[data-dialog-ok]');
  await page.waitForTimeout(200);
  const purged = await page.evaluate(() => ({ n: ['transactions', 'debts', 'goals', 'accounts', 'holdings'].map(k => Store.state[k].length).join(), saved: JSON.parse(localStorage.getItem(Store.KEY) || '{}'), box: (document.querySelector('.modal') || {}).textContent || '' }));
  ok(purged.n === '0,0,0,0,0' && (purged.saved.transactions || []).length === 0 && /Your data has been erased/.test(purged.box), 'typing "Delete" erases everything (memory and storage) and confirms it', [purged.n, purged.box.slice(0, 80)]);
  await page.click('[data-dialog-ok]');
  // Smart CSV import (engine, streams, rules) — see e2e-imp.js.
  await require('./e2e-imp.js')(page, ok);
  // Spending donut: categories of the month, a slice opens its transactions, per person.
  await page.evaluate(() => { Store.reset('example'); Store.ui.spending = null; App.changed({ structural: true }); App.go('transacciones/reportes'); });
  await page.waitForTimeout(400);
  const sp = await page.evaluate(() => { const t = new Date(), y = t.getFullYear(), m = t.getMonth(); const r = Engine.spendingBreakdown(Store.state.transactions, { from: Engine.isoDate(new Date(y, m, 1)), to: Engine.isoDate(new Date(y, m + 1, 0)) }); return { total: Fmt.money(r.total), first: r.rows[0].key, n: r.rows.length, rows: document.querySelectorAll('#spend-legend .spend-row').length, center: document.getElementById('spend-center').textContent, chart: !!UI.chartInstance('spend-donut') }; });
  ok(sp.chart && sp.rows === sp.n && sp.n <= 7 && sp.center.includes(sp.total), 'spending: donut, total in the middle, one row per slice', sp);
  await page.click('#spend-legend .spend-row >> nth=0');
  await page.waitForTimeout(150);
  const lvl2 = await page.evaluate(() => ({ cat: Store.ui.spending.cat, banner: document.getElementById('spend-detail').textContent, center: document.getElementById('spend-center').textContent, rows: document.querySelectorAll('#spend-legend .spend-row').length, back: !!document.querySelector('[data-action="spend.back"]') }));
  ok(lvl2.cat === 'Vivienda' && /Housing/.test(lvl2.banner) && /of all spending/.test(lvl2.banner) && /period before/.test(lvl2.banner) && /Housing/.test(lvl2.center) && lvl2.rows >= 1 && lvl2.back, 'spending: a category opens its subcategories with a banner', lvl2);
  await page.click('#spend-legend .spend-row >> nth=0');
  await page.click('[data-action="spend.txns"]');
  await page.waitForTimeout(150);
  const lvl3 = await page.evaluate(() => ({ sub: Store.ui.spending.sub, payees: document.querySelectorAll('#spend-detail .acd-txn').length }));
  ok(!!lvl3.sub && lvl3.payees >= 1, 'spending: a subcategory and its transactions by payee', lvl3);
  await page.click('[data-action="spend.back"]');
  await page.waitForTimeout(150);
  ok(await page.evaluate(() => !Store.ui.spending.cat && document.getElementById('spend-detail').textContent === ''), 'spending: back to all categories');
  await page.click('[data-action="spend.range"][data-range="6m"]');
  await page.selectOption('#spend-who', String(-1));
  await page.waitForTimeout(150);
  const sp6 = await page.evaluate(() => ({ center: document.getElementById('spend-center').textContent, active: document.querySelector('[data-action="spend.range"].active').dataset.range }));
  ok(sp6.active === '6m' && /Spent/.test(sp6.center) && !sp6.center.includes(sp.total), 'spending: 6 months, household only', sp6);
  // Trends: stacked areas by category with an income line; 1Y; one category; one account.
  await page.click('[data-action="trends.months"][data-months="12"]');
  await page.waitForTimeout(200);
  const tr1 = await page.evaluate(() => { const c = UI.chartInstance('trends-chart'); return { labels: c.data.labels.length, sets: c.data.datasets.map(d => d.label), stacked: c.options.scales.y.stacked, rows: document.querySelectorAll('#trends-table tr').length }; });
  ok(tr1.labels === 12 && tr1.rows === 12 && tr1.stacked && tr1.sets.includes('Income') && tr1.sets.length >= 3, 'trends: 12 months stacked by category with income', tr1);
  await page.selectOption('#trends-category', 'Alimentación');
  await page.waitForTimeout(200);
  const tr2 = await page.evaluate(() => UI.chartInstance('trends-chart').data.datasets.map(d => d.label));
  ok(!tr2.includes('Income') && tr2.length >= 1 && !tr2.includes('Food'), 'trends: one category shows its subcategories', tr2);
  await page.evaluate(() => { Store.state.transactions.push({ id: 999001, date: Engine.isoDate(new Date()), type: 'Gasto', parentCategory: 'Ocio', category: 'Cine', description: 'Movies', amount: 33, accountId: 77 }); App.update(); });
  await page.selectOption('#trends-category', '');
  await page.evaluate(() => { const s = document.getElementById('trends-account'); s.insertAdjacentHTML('beforeend', '<option value="77">x</option>'); s.value = '77'; s.dispatchEvent(new Event('change', { bubbles: true })); });
  await page.waitForTimeout(200);
  const tr3 = await page.evaluate(() => { const c = UI.chartInstance('trends-chart'); return c.data.datasets.map(d => d.label + ':' + d.data.reduce((a, v) => a + v, 0)); });
  ok(tr3.length === 2 && /:33$/.test(tr3[0]) && tr3[1] === 'Income:0', 'trends: one account', tr3);
  await page.evaluate(() => { Store.state.transactions = Store.state.transactions.filter(t => t.id !== 999001); Store.ui.trends = null; App.update(); });
  // Budget bubbles: one per category, sized by plan, colored by share spent; tap → its lines.
  await page.evaluate(() => { Store.reset('example'); Store.ui.month = 'base'; Store.ui.budgetBubbles = false; App.changed({ structural: true }); App.go('presupuesto/plan'); });
  await page.waitForTimeout(300);
  await page.click('[data-action="budget.bubbles"]');
  await page.waitForTimeout(200);
  const bub = await page.evaluate(() => { const b = [...document.querySelectorAll('#bs-bubbles .bubble')]; const sizes = b.map(x => x.offsetWidth); return { n: b.length, grid: document.querySelector('#bud-simple .bs-grid').classList.contains('hidden'), first: b[0] && b[0].textContent.replace(/\s+/g, ' '), desc: sizes.every((v, i) => !i || v <= sizes[i - 1]), states: new Set(b.map(x => x.className.match(/is-(\w+)/)[1])).size, pressed: document.querySelector('[data-action="budget.bubbles"]').getAttribute('aria-pressed') }; });
  ok(bub.n >= 5 && bub.grid && /Housing/.test(bub.first) && bub.desc && bub.states >= 2 && bub.pressed === 'true', 'bubbles: one per category, biggest plan first, colored by spending', bub);
  await page.click('#bs-bubbles .bubble >> nth=0');
  await page.waitForTimeout(200);
  const bsheet = await page.evaluate(() => { const m = document.querySelector('.modal-backdrop.sheet'); return m ? { title: m.querySelector('.modal-title').textContent, rows: m.querySelectorAll('.bub-line').length, pace: !!m.querySelector('#bub-pace') } : null; });
  ok(bsheet && /Housing/.test(bsheet.title) && bsheet.rows >= 1, 'bubbles: tapping one lists its lines', bsheet);
  // The slider changes the line's planned amount; the pace says where spending would be by today.
  const slid = await page.evaluate(() => { const el = document.querySelector('.bub-slider'); const id = el.dataset.id; el.value = '1500'; el.dispatchEvent(new Event('input', { bubbles: true })); const it = Engine.monthItems(Store.active(), 'base').find(x => String(x.id) === id); return { real: it.real, label: el.closest('.bub-line').querySelector('[data-planned]').textContent, pace: document.getElementById('bub-pace').textContent }; });
  ok(slid.real === 1500 && /1,500/.test(slid.label) && /By today|spent of/.test(slid.pace), 'bubbles: a slider changes the plan; the pace shows', slid);
  await page.click('.modal-backdrop.sheet [data-action="budget.bubbleLine"] >> nth=0');
  await page.waitForTimeout(250);
  ok(await page.evaluate(() => document.querySelectorAll('.modal-backdrop.sheet').length === 1 && !document.querySelector('[data-action="budget.bubbleLine"]')), 'bubbles: a line opens its details');
  await page.keyboard.press('Escape');
  await page.evaluate(() => document.querySelectorAll('.modal-backdrop.sheet').forEach(m => m.remove()));
  await page.click('[data-action="budget.bubbles"]');
  await page.waitForTimeout(150);
  ok(await page.evaluate(() => !document.querySelector('#bud-simple .bs-grid').classList.contains('hidden') && document.getElementById('bs-bubbles').classList.contains('hidden')), 'bubbles: back to cards');
  // Cash flow: daily balance ahead, red below $0, cash events added, shown and removed (undoable).
  await page.evaluate(() => { Store.reset('example'); Store.ui.flowDays = 30; App.changed({ structural: true }); App.go('resumen'); });
  await page.waitForTimeout(300);
  const fl1 = await page.evaluate(() => { const c = UI.chartInstance('flow-chart'); return { n: c.data.labels.length, today: c.options.plugins.todayLine.index, note: document.getElementById('flow-note').textContent }; });
  ok(fl1.n === 30 && fl1.today === 0 && /lowest point|Below \$0/i.test(fl1.note), 'cash flow: 30 days from today', fl1);
  await page.evaluate(() => { const d = new Date(); d.setDate(d.getDate() + 5); document.getElementById('flow-date').value = Engine.isoDate(d); document.getElementById('dash-flow-card').open = true; });
  await page.fill('#flow-name', 'Car repair');
  await page.fill('#flow-amount', '25000');
  await page.click('[data-action="flow.add"]');
  await page.waitForTimeout(300);
  const fl2 = await page.evaluate(() => { const c = UI.chartInstance('flow-chart'); const ds = c.data.datasets[0]; return { ev: Store.state.cashEvents.map(e => e.name + ':' + e.amount).join(), marked: ds.pointRadius.filter(r => r > 0).length, neg: Math.min(...ds.data) < 0, below: typeof ds.fill === 'object' && !!ds.fill.below, list: document.getElementById('flow-events').textContent, cal: Cash.events(Engine.isoDate(new Date()), Engine.isoDate(new Date(Date.now() + 9 * 864e5))).list.some(e => e.kind === 'oneoff') }; });
  ok(fl2.ev === 'Car repair:-25000' && fl2.marked === 1 && fl2.neg && fl2.below && /Car repair/.test(fl2.list) && fl2.cal, 'cash flow: a cash event shows on the chart, the list and the calendar', fl2);
  await page.click('[data-action="flow.days"][data-days="90"]');
  await page.click('[data-action="flow.del"]');
  await page.waitForTimeout(250);
  ok(await page.evaluate(() => Store.state.cashEvents.length === 0 && UI.chartInstance('flow-chart').data.labels.length === 90), 'cash flow: 90 days; removing the event');
  await page.click('.toast-undo button, .toast-undo [data-toast-action], .toast-undo .toast-btn').catch(() => page.evaluate(() => App.undo()));
  await page.waitForTimeout(250);
  ok(await page.evaluate(() => Store.state.cashEvents.length === 1), 'cash flow: removing is undoable');
  // Debts: each debt stacked month by month until debt-free; the table has rate and payment.
  await page.evaluate(() => { Store.reset('example'); App.changed({ structural: true }); App.go('futuro/metas'); });
  await page.waitForTimeout(300);
  const ds = await page.evaluate(() => { const c = UI.chartInstance('debt-stack-chart'), p = App.buildContext().debts; const sets = c.data.datasets; const last = c.data.labels.length - 1; return { n: sets.length, debts: Store.state.debts.filter(d => d.balance > 0).length, stacked: c.options.scales.y.stacked, len: c.data.labels.length, months: p.months, endZero: sets.every(d => d.data[last] === 0), start: Math.round(sets.reduce((t, d) => t + d.data[0], 0)), total: Math.round(Store.state.debts.reduce((t, d) => t + (Number(d.balance) || 0), 0)), head: [...document.querySelectorAll('#debt-ladder-table')].length && document.querySelector('#debt-ladder-table').closest('table').querySelector('thead').textContent, row: document.querySelector('#debt-ladder-table tr').textContent }; });
  ok(ds.n === ds.debts && ds.stacked && ds.len === ds.months + 1 && ds.endZero && Math.abs(ds.start - ds.total) <= ds.n && /Rate/.test(ds.head) && /Payment/.test(ds.head) && /%/.test(ds.row), 'debts: stacked per debt to debt-free, table with rate and payment', ds);
  // Net worth over time: assets up, liabilities down, the net worth line; 6M / 1Y / All; table.
  await page.evaluate(() => { Store.reset('example'); Store.ui.nwRange = 12; App.changed({ structural: true }); App.go('patrimonio'); });
  await page.waitForTimeout(300);
  const nwm = await page.evaluate(() => { const c = UI.chartInstance('nw-month-chart'), h = Store.state.netWorthHistory.slice(-12), [line, a, l] = c.data.datasets; return { n: c.data.labels.length, line: line.type === 'line' && line.data.at(-1) === h.at(-1).value, a: a.data.at(-1) === h.at(-1).assets, l: l.data.at(-1) === -h.at(-1).liabilities, rows: document.querySelectorAll('#nw-month-table tr').length, change: document.getElementById('nw-month-change').textContent }; });
  ok(nwm.n === 12 && nwm.line && nwm.a && nwm.l && nwm.rows === 12 && /since/.test(nwm.change), 'net worth: assets, liabilities and the line, 1 year', nwm);
  await page.click('[data-action="nw.range"][data-months="6"]');
  await page.waitForTimeout(150);
  const n6 = await page.evaluate(() => UI.chartInstance('nw-month-chart').data.labels.length);
  await page.click('[data-action="nw.range"][data-months="0"]');
  await page.waitForTimeout(150);
  ok(n6 === 6 && await page.evaluate(() => UI.chartInstance('nw-month-chart').data.labels.length === Store.state.netWorthHistory.length), 'net worth: 6M and All', n6);
  // Money tools bar: every tool one tap away; Help grid with a how-to per tool that opens it.
  await page.evaluate(() => { Store.reset('example'); App.changed({ structural: true }); App.go('resumen'); });
  await page.waitForTimeout(200);
  ok(await page.$$eval('#tools-bar a', a => a.length) === 10, 'tools bar: 10 tools');
  await page.click('#tools-bar a[data-focus="spend-card"]');
  await page.waitForTimeout(300);
  ok(await page.evaluate(() => Store.ui.tab === 'transacciones' && Math.abs(document.getElementById('spend-card').getBoundingClientRect().top) < 400), 'tools bar: Spending opens the donut');
  await page.evaluate(() => App.go('resumen'));
  await page.click('[data-action="tools.help"]');
  await page.waitForTimeout(150);
  ok(await page.$$eval('.help-grid button', b => b.length) === 12, 'help: 12 tiles');
  await page.click('[data-action="tools.topic"][data-key="debts"]');
  await page.waitForTimeout(100);
  ok(/snowball/.test(await page.textContent('.modal-backdrop.sheet')), 'help: a topic explains the tool');
  await page.click('[data-action="tools.go"]');
  await page.waitForTimeout(300);
  ok(await page.evaluate(() => Store.ui.tab === 'futuro' && !document.querySelector('.modal-backdrop.sheet')), 'help: Open goes to the tool');
  // All accounts: everything by type with totals; add a manual property and a loan; open a row.
  await page.evaluate(() => { Store.reset('example'); App.changed({ structural: true }); App.go('patrimonio'); });
  await page.waitForTimeout(300);
  const hub = await page.evaluate(() => { const h = AccountsHub.last; return { groups: [...document.querySelectorAll('#hub-body .hub-group')].map(g => g.id.slice(4)), rows: document.querySelectorAll('#hub-body .hub-row').length, n: h.groups.reduce((t, g) => t + g.rows.length, 0), owedRed: !!document.querySelector('#hub-loan header .text-red-600'), net: Math.round(h.net) }; });
  ok(hub.groups.includes('checking') && hub.groups.includes('card') && hub.groups.includes('property') && hub.rows === hub.n && hub.owedRed, 'accounts hub: groups by type, owed in red', hub);
  await page.click('[data-action="hub.add"]');
  await page.waitForTimeout(150);
  await page.selectOption('#hub-new-type', 'property');
  await page.waitForTimeout(100);
  await page.selectOption('#hub-new-sub', 'Vehículo');
  await page.fill('#hub-new-name', 'Camper');
  await page.fill('#hub-new-bal', '12000');
  await page.click('[data-action="hub.save"]');
  await page.waitForTimeout(250);
  ok(await page.evaluate(() => Store.state.assets.some(a => a.name === 'Camper' && a.category === 'Vehículo' && a.purchaseValue === 12000) && /Camper/.test(document.getElementById('hub-property').textContent)), 'accounts hub: add a property');
  await page.click('[data-action="hub.add"]');
  await page.selectOption('#hub-new-type', 'tarjeta');
  await page.fill('#hub-new-name', 'Store card');
  await page.fill('#hub-new-bal', '300');
  await page.click('[data-action="hub.save"]');
  await page.waitForTimeout(250);
  ok(await page.evaluate(() => Store.state.accounts.some(a => a.name === 'Store card' && a.kind === 'tarjeta' && a.balance === -300) && /Store card/.test(document.getElementById('hub-card').textContent)), 'accounts hub: a card is what you owe');
  await page.click('#hub-loan .hub-row >> nth=0');
  await page.waitForTimeout(300);
  ok(await page.evaluate(() => /Auto loan|Student loan|Other debt/.test(document.querySelector('.modal-backdrop.sheet').textContent)), 'accounts hub: a loan opens its details');
  await page.evaluate(() => document.querySelectorAll('.modal-backdrop.sheet').forEach(m => m.remove()));
  // Account details: Activity (12 months in/out + transactions) and Details synced with the debt.
  await page.evaluate(() => { Store.reset('example'); App.changed({ structural: true }); App.go('patrimonio'); });
  await page.waitForTimeout(300);
  await page.click('#hub-checking .hub-row >> nth=0');
  await page.waitForTimeout(300);
  const acd1 = await page.evaluate(() => { const c = UI.chartInstance('acd-chart'); return { bars: c && c.data.labels.length, sets: c && c.data.datasets.map(d => d.label).join(), rows: document.querySelectorAll('.acd-txn').length }; });
  ok(acd1.bars === 12 && /Money out/.test(acd1.sets) && acd1.rows > 10, 'account details: activity chart and transactions', acd1);
  await page.evaluate(() => document.querySelector('.modal-backdrop.sheet [data-dialog-cancel]').click());
  await page.click('#hub-card .hub-row >> nth=0');
  await page.waitForTimeout(200);
  await page.click('[data-action="acd.tab"][data-tab="details"]');
  await page.waitForTimeout(150);
  await page.evaluate(() => { const set = (f, v) => { const el = document.querySelector(`.acd-fields [data-field="${f}"]`); el.value = v; el.dispatchEvent(new Event('change', { bubbles: true })); }; set('rate', '19.99'); set('minPayment', '160'); set('creditLimit', '10000'); set('dueDay', '15'); });
  await page.waitForTimeout(200);
  const acd2 = await page.evaluate(() => { const d = Store.state.debts.find(x => x.kind === 'tarjeta'); return { rate: d.rate, min: d.minPayment, due: d.dueDay, limit: d.creditLimit }; });
  ok(acd2.rate === 19.99 && acd2.min === 160 && acd2.due === 15 && acd2.limit === 10000, 'account details: details change the debt the snowball uses', acd2);
  await page.evaluate(() => document.querySelector('.modal-backdrop.sheet [data-dialog-cancel]').click());
  // An unlinked card account becomes a debt from its details.
  await page.evaluate(() => { Store.state.accounts.push({ id: 99, name: 'Store card', kind: 'tarjeta', balance: -420, updatedAt: Engine.isoDate(new Date()) }); App.changed({ structural: true }); AccountsHub.openDetails('account', 99); });
  await page.waitForTimeout(200);
  await page.click('[data-action="acd.tab"][data-tab="details"]');
  await page.click('[data-action="acd.toDebt"]');
  await page.waitForTimeout(200);
  ok(await page.evaluate(() => { const a = Store.state.accounts.find(x => x.id === 99), d = Store.state.debts.find(x => x.id === a.debtId); return !!d && d.balance === 420 && d.kind === 'tarjeta' && AccountsHub.last.groups.find(g => g.key === 'card').rows.filter(r => r.name === 'Store card').length === 1; }), 'account details: add an unlinked card to the debts, counted once');
  await page.evaluate(() => document.querySelectorAll('.modal-backdrop.sheet').forEach(m => m.remove()));
  // Transactions toolbar: date range presets, ‹ › stepping, accounts, download.
  await page.evaluate(() => { Store.reset('example'); Store.ui.txnFilters = { year: 'all', month: 'all', type: 'all', category: 'all' }; Store.ui.txnLimit = 5000; App.changed({ structural: true }); App.go('transacciones/lista'); });
  await page.waitForTimeout(250);
  const rows = () => page.evaluate(() => [...document.querySelectorAll('#txn-body .txn-item')].map(r => { const t = Store.state.transactions.find(x => x.id === Number(r.dataset.row)); return { d: t.date, a: t.accountId || null }; }));
  await page.click('[data-action="txn.rangePick"]');
  await page.click('[data-action="txn.rangeSet"][data-range="last-month"]');
  await page.waitForTimeout(200);
  const lm = await page.evaluate(() => Engine.rangeFor('last-month', new Date()));
  let r1 = await rows();
  ok(r1.length > 20 && r1.every(r => r.d >= lm.from && r.d <= lm.to) && await page.textContent('#txn-range-label') === 'Last month', 'transactions: last month', r1.length);
  await page.click('[data-action="txn.rangeStep"][data-dir="-1"]');
  await page.waitForTimeout(200);
  const prev = await page.evaluate((lm) => Engine.shiftRange(lm.from, lm.to, -1), lm);
  r1 = await rows();
  ok(r1.length > 20 && r1.every(r => r.d >= prev.from && r.d <= prev.to) && /–/.test(await page.textContent('#txn-range-label')), 'transactions: ‹ steps a month back', prev);
  await page.click('[data-action="txn.accounts"]');
  await page.waitForTimeout(150);
  await page.evaluate(() => { const w = Store.state.accounts.find(a => a.kind === 'efectivo'); document.querySelectorAll('.acct-pick').forEach(c => { c.checked = c.value === String(w.id); }); });
  await page.click('[data-action="txn.acctApply"]');
  await page.waitForTimeout(200);
  const wallet = await page.evaluate(() => Store.state.accounts.find(a => a.kind === 'efectivo').id);
  r1 = await rows();
  ok(r1.length > 0 && r1.every(r => r.a === wallet) && await page.textContent('#txn-accts-label') === '1 account', 'transactions: one account', r1.length);
  const csv = await page.evaluate(async () => { let got = null; const keep = Native.saveFile; Native.saveFile = (name, text) => { got = { name, text }; return Promise.resolve('saved'); }; UI.run('txn.download', {}); Native.saveFile = keep; return got; });
  ok(csv && /^transactions_\d{4}-\d\d-01_/.test(csv.name) && csv.text.trim().split('\n').length === r1.length + 1 && /Date,Payee,Category/.test(csv.text), 'transactions: download what is shown', csv && csv.name);
  // A Month close link (year + month) still works: it becomes that month.
  await page.evaluate(() => { Store.ui.txnFilters = { year: '2026', month: '3', type: 'Gasto', category: 'all', member: 'all' }; App.update(); });
  await page.waitForTimeout(150);
  r1 = await rows();
  ok(r1.length > 0 && r1.every(r => r.d.startsWith('2026-03')), 'transactions: an old year/month filter becomes a range');
  await page.evaluate(() => { Store.ui.txnFilters = { year: 'all', month: 'all', type: 'all', category: 'all' }; Store.ui.txnLimit = null; App.update(); });
  // Transaction details: tap a row; payee, memo, tag, category; flag; exclude (and include again).
  await page.evaluate(() => { Store.reset('example'); Store.ui.txnFilters = { year: 'all', month: 'all', type: 'all', category: 'all' }; Store.ui.txnSearch = ''; App.changed({ structural: true }); App.go('transacciones/lista'); });
  await page.waitForTimeout(250);
  const tid = await page.evaluate(() => Number(document.querySelector('#txn-body .txn-item:not(.row-editing)').dataset.row));
  await page.click(`#txn-body .txn-item[data-row="${tid}"] .txn-main`);
  await page.waitForTimeout(200);
  ok(await page.evaluate(() => /Transaction details/.test(document.querySelector('.modal-backdrop.sheet').textContent)), 'transaction details: tapping a row opens them');
  const setDet = (f, v) => page.evaluate(([f, v]) => { const el = document.querySelector(`#tdt-body [data-field="${f}"]`); el.value = v; el.dispatchEvent(new Event('change', { bubbles: true })); }, [f, v]);
  await setDet('description', 'Corner Store');
  await setDet('memo', 'milk and bread');
  await page.evaluate(() => { const el = document.querySelector('#tdt-body [data-change="tdt.tag"]'); el.value = 'weekly'; el.dispatchEvent(new Event('change', { bubbles: true })); });
  await page.click('[data-action="tdt.category"]');
  await page.waitForTimeout(150);
  await page.fill('#tdt-cat-q', 'coffee');
  await page.waitForTimeout(100);
  await page.click('[data-action="tdt.catSet"][data-sub="Cafetería"]');
  await page.waitForTimeout(150);
  const det = await page.evaluate((id) => { const t = Store.state.transactions.find(x => x.id === id); return { d: t.description, m: t.memo, tags: (t.tags || []).join(), c: t.parentCategory + '/' + t.category }; }, tid);
  ok(det.d === 'Corner Store' && det.m === 'milk and bread' && det.tags === 'weekly' && det.c === 'Alimentación/Cafetería', 'transaction details: payee, memo, tag and category (search)', det);
  await page.click('[data-action="tdt.menu"]');
  await page.click('[data-action="tdt.flag"]');
  await page.waitForTimeout(100);
  await page.evaluate(() => document.querySelectorAll('.modal-backdrop.sheet').forEach(m => m.remove()));
  await page.selectOption('#txn-f-origin', 'flagged');
  await page.waitForTimeout(150);
  ok(await page.evaluate((id) => { const r = [...document.querySelectorAll('#txn-body .txn-item')]; return r.length === 1 && Number(r[0].dataset.row) === id && !!r[0].querySelector('.fa-flag'); }, tid), 'transaction details: flagged filter');
  await page.selectOption('#txn-f-origin', 'all');
  await page.evaluate((id) => TxnDetails.open(id), tid);
  await page.waitForTimeout(150);
  const spentBefore = await page.evaluate((id) => { const t = Store.state.transactions.find(x => x.id === id); return Engine.spendingBreakdown(Store.state.transactions, { from: t.date, to: t.date }).total; }, tid);
  await page.click('[data-action="tdt.menu"]');
  await page.click('[data-action="tdt.exclude"]');
  await page.waitForTimeout(200);
  const exc = await page.evaluate((id) => { const t = Store.state.excludedTxns.find(x => x.id === id); return { gone: !Store.state.transactions.some(x => x.id === id), kept: !!t, spent: t && Engine.spendingBreakdown(Store.state.transactions, { from: t.date, to: t.date }).total, banner: /Excluded/.test(document.querySelector('.modal-backdrop.sheet').textContent) }; }, tid);
  ok(exc.gone && exc.kept && exc.banner && exc.spent < spentBefore, 'transaction details: excluded no longer counts', { exc, spentBefore });
  await page.evaluate(() => document.querySelectorAll('.modal-backdrop.sheet').forEach(m => m.remove()));
  await page.selectOption('#txn-f-origin', 'excluded');
  await page.waitForTimeout(150);
  ok(await page.evaluate((id) => [...document.querySelectorAll('#txn-body .txn-item')].map(r => Number(r.dataset.row)).join() === String(id), tid), 'transaction details: the Excluded filter shows it');
  await page.click(`#txn-body .txn-item[data-row="${tid}"] .txn-main`);
  await page.waitForTimeout(150);
  await page.click('[data-action="tdt.menu"]');
  await page.click('[data-action="tdt.exclude"]');
  await page.waitForTimeout(200);
  ok(await page.evaluate((id) => Store.state.transactions.some(x => x.id === id) && !Store.state.excludedTxns.length, tid), 'transaction details: include again');
  await page.click('[data-action="tdt.menu"]');
  await page.click('[data-action="tdt.split"]');
  await page.waitForTimeout(250);
  ok(await page.evaluate(() => !!document.querySelector('.modal-backdrop') && !document.getElementById('tdt-body')), 'transaction details: Split opens the split');
  await page.keyboard.press('Escape');
  await page.evaluate(() => document.querySelectorAll('.modal-backdrop').forEach(m => m.remove()));
  await page.evaluate(() => document.querySelectorAll('.modal-backdrop.sheet').forEach(m => m.remove()));
  await page.selectOption('#txn-f-origin', 'all');
  // Smart budget: suggest from the last 90 days, apply the checked lines (undoable).
  await page.evaluate(() => { Store.reset('example'); Store.ui.month = 'base'; Store.ui.budgetBubbles = false; App.changed({ structural: true }); App.go('presupuesto/plan'); });
  await page.waitForTimeout(250);
  await page.click('[data-action="budget.suggest"]');
  await page.waitForTimeout(250);
  const sug = await page.evaluate(() => ({ rows: document.querySelectorAll('.sug-pick').length, checked: document.querySelectorAll('.sug-pick:checked').length }));
  ok(sug.rows > 10 && sug.checked >= 1 && sug.checked < sug.rows, 'smart budget: suggestions with the different ones checked', sug);
  const want = await page.evaluate(() => { const c = document.querySelector('.sug-pick:checked'); const row = c.closest('tr'); return { name: row.children[1].textContent, sugg: row.children[3].querySelector('span').textContent }; });
  await page.click('[data-action="budget.suggestApply"]');
  await page.waitForTimeout(250);
  const applied = await page.evaluate((w) => { const it = Engine.monthItems(Store.active(), 'base').find(x => I18n.t(x.name) === w.name); return it && Fmt.money0(it.real); }, want);
  ok(applied === want.sugg, 'smart budget: the checked line takes the suggestion', { want, applied });
  await page.evaluate(() => App.undo());
  await page.waitForTimeout(150);
  // Trends drill-down: tap a month → categories vs average → subcategories → transactions.
  await page.evaluate(() => { Store.reset('example'); Store.ui.trends = { months: 6, category: '', account: '' }; App.changed({ structural: true }); App.go('transacciones/reportes'); });
  await page.waitForTimeout(300);
  ok(/Tap a month/.test(await text(page, 'trends-drill')), 'trends drill: a hint before tapping');
  const tc = await page.$('#trends-chart'); await tc.scrollIntoViewIfNeeded(); const tb = await tc.boundingBox();
  await page.mouse.click(tb.x + tb.width * 0.5, tb.y + tb.height * 0.5);
  await page.waitForTimeout(250);
  const d1 = await page.evaluate(() => ({ month: (Store.ui.trends.drill || {}).month, rows: document.querySelectorAll('#trends-drill .spend-row').length, avg: /vs avg|= avg/.test(document.getElementById('trends-drill').textContent) }));
  ok(!!d1.month && d1.rows >= 3 && d1.avg, 'trends drill: a month shows its categories vs the average', d1);
  await page.evaluate(() => { const b = [...document.querySelectorAll('#trends-drill .spend-row')].find(x => x.dataset.key === 'Alimentación'); b.click(); });
  await page.waitForTimeout(200);
  const d2 = await page.evaluate(() => ({ cat: Store.ui.trends.drill.cat, head: document.querySelector('#trends-drill strong').textContent, rows: document.querySelectorAll('#trends-drill .spend-row').length }));
  ok(d2.cat === 'Alimentación' && /Food/.test(d2.head) && d2.rows >= 2, 'trends drill: a category shows its subcategories', d2);
  await page.click('#trends-drill .spend-row >> nth=0');
  await page.waitForTimeout(200);
  const d3 = await page.evaluate(() => ({ sub: Store.ui.trends.drill.sub, txns: document.querySelectorAll('#trends-drill .acd-txn').length }));
  ok(!!d3.sub && d3.txns >= 1, 'trends drill: a subcategory lists its transactions', d3);
  await page.click('[data-action="trends.up"]');
  await page.click('[data-action="trends.up"]');
  await page.waitForTimeout(150);
  ok(await page.evaluate(() => !Store.ui.trends.drill.cat && !Store.ui.trends.drill.sub), 'trends drill: back up to the month');
  // Debt payoff controls: "what if" extra slider, add it to the budget; a debt's schedule.
  await page.evaluate(() => { Store.reset('example'); Store.ui.debtExtraTry = 0; App.changed({ structural: true }); App.go('futuro/metas'); });
  await page.waitForTimeout(300);
  const dBefore = await page.evaluate(() => ({ m: App.buildContext().debts.months, extra: App.buildContext().debtExtraRubros }));
  await page.evaluate(() => { const el = document.getElementById('debt-extra'); el.value = 300; el.dispatchEvent(new Event('input', { bubbles: true })); });
  await page.waitForTimeout(150);
  ok(/sooner/.test(await text(page, 'debt-extra-result')) && /less interest/.test(await text(page, 'debt-extra-result')), 'debts: what-if extra shows sooner and less interest', await text(page, 'debt-extra-result'));
  await page.click('[data-action="debt.extraApply"]');
  await page.waitForTimeout(250);
  const dAfter = await page.evaluate(() => ({ m: App.buildContext().debts.months, extra: App.buildContext().debtExtraRubros, slider: document.getElementById('debt-extra').value }));
  ok(dAfter.extra === dBefore.extra + 300 && dAfter.m < dBefore.m && dAfter.slider === '0', 'debts: add it to the budget', { dBefore, dAfter });
  await page.click('[data-action="debt.schedule"] >> nth=0');
  await page.waitForTimeout(250);
  const sch = await page.evaluate(() => { const rows = [...document.querySelectorAll('.modal-backdrop.sheet tbody tr')]; return { n: rows.length, last: rows.length && rows[rows.length - 1].lastElementChild.textContent, first: rows[0] && rows[0].children.length }; });
  ok(sch.n > 3 && sch.last === '$0.00' && sch.first === 5, 'debts: a schedule month by month down to $0', sch);
  await page.evaluate(() => document.querySelectorAll('.modal-backdrop.sheet').forEach(m => m.remove()));
  // Balance sheet: own vs owe by type; a type opens to its accounts; a property value edited in place.
  await page.evaluate(() => { Store.reset('example'); Store.ui.nwOpen = null; App.changed({ structural: true }); App.go('patrimonio'); });
  await page.waitForTimeout(250);
  const bs1 = await page.evaluate(() => ({ own: document.querySelectorAll('#nw-sheet-body .sheet-side')[0].textContent, owe: document.querySelectorAll('#nw-sheet-body .sheet-side')[1].textContent, types: document.querySelectorAll('#nw-sheet-body .sheet-head').length, net: AccountsHub.last.net }));
  ok(/What you own/.test(bs1.own) && /What you owe/.test(bs1.owe) && bs1.types >= 6, 'balance sheet: own and owe by type', bs1);
  await page.click('[data-action="sheet.toggle"][data-key="property"]');
  await page.waitForTimeout(150);
  await page.evaluate(() => { const el = document.querySelector('[data-change="sheet.assetValue"]'); el.value = String(Number(el.value) + 10000); el.dispatchEvent(new Event('change', { bubbles: true })); });
  await page.waitForTimeout(200);
  const bs2 = await page.evaluate(() => ({ net: AccountsHub.last.net, headline: document.querySelector('.sheet-net').textContent }));
  ok(Math.round(bs2.net - bs1.net) === 10000 && /Net worth/i.test(bs2.headline), 'balance sheet: a property value changes net worth', { bs1: bs1.net, bs2 });
  await page.click('[data-action="sheet.toggle"][data-key="loan"]');
  await page.waitForTimeout(150);
  await page.click('#nw-sheet-body .sheet-rows button.sheet-row >> nth=0');
  await page.waitForTimeout(200);
  ok(await page.evaluate(() => /Account details/.test(document.querySelector('.modal-backdrop.sheet').textContent)), 'balance sheet: an account opens its details');
  await page.evaluate(() => document.querySelectorAll('.modal-backdrop.sheet').forEach(m => m.remove()));
  // First-run setup guide: one sheet, five short steps, opened again from Settings.
  await page.evaluate(() => { Store.reset('example'); App.changed({ structural: true }); });
  await go(page, 'config');
  await page.click('[data-action="setup.open"]');
  await page.waitForTimeout(150);
  await page.click('[data-action="setup.start"]');
  await page.waitForTimeout(150);
  await page.click('[data-dialog-ok]');
  await page.waitForTimeout(200);
  ok(await page.evaluate(() => !Store.state.settings.sample && Store.state.transactions.length === 0), 'setup: the example makes way for an empty plan');
  await page.fill('#su-names', 'Ana, Luis');
  await page.click('[data-action="setup.next"]');
  await page.waitForTimeout(100);
  await page.selectOption('#su-type', 'hourly');
  await page.waitForTimeout(100);
  await page.fill('#su-rate', '25');
  await page.fill('#su-hours', '40');
  await page.selectOption('#su-freq', 'biweekly');
  await page.fill('#su-next', '2026-10-16');
  await page.click('[data-action="setup.next"]');
  await page.waitForTimeout(100);
  await page.fill('#su-checking', '1200');
  await page.fill('#su-card', '800');
  await page.click('[data-action="setup.next"]');
  await page.waitForTimeout(100);
  await page.fill('.su-bill >> nth=0', '1100');
  await page.click('[data-action="setup.next"]');
  await page.waitForTimeout(100);
  await page.fill('#su-d0-name', 'Visa');
  await page.fill('#su-d0-bal', '800');
  await page.fill('#su-d0-rate', '24');
  await page.click('[data-action="setup.next"]');
  await page.waitForTimeout(150);
  const su = await page.evaluate(() => { const s = Store.state, y = Store.active(); return { names: s.members.map(m => m.name).join(','), type: y.payType, rate: y.hourly && y.hourly.rate, sueldo: y.sueldo, sched: s.settings.paySchedule, accts: s.accounts.map(a => a.kind + ':' + a.balance + ':' + (a.debtId || '')).join(','), bill: y.budgetBase.filter(i => !i.link)[0].prep, debt: s.debts.map(d => d.name + ':' + d.kind + ':' + d.minPayment).join(','), seen: s.settings.setupSeen }; });
  ok(su.names === 'Ana,Luis' && su.type === 'hourly' && su.rate === 25 && Math.round(su.sueldo) === 4333 && su.sched.interval === 2 && su.sched.anchor === '2026-10-16'
    && su.accts === 'corriente:1200:,tarjeta:-800:1' && su.bill === 1100 && su.debt === 'Visa:tarjeta:25' && !su.seen, 'setup: each step saves what it asked', su);
  ok(/Your plan is set up/.test(await page.textContent('.modal-backdrop:not(.hidden)')), 'setup: done screen');
  await page.click('[data-action="setup.close"]');
  await page.waitForTimeout(200);
  ok(await page.evaluate(() => Store.state.settings.setupSeen && Store.ui.tab === 'presupuesto' && !document.querySelector('.modal-backdrop:not(.hidden)')), 'setup: closing marks it seen and goes to the budget');
  // Walking through again keeps your data: no example offer, the checking balance is updated, not doubled.
  await page.evaluate(() => UI.run('setup.open', {}));
  await page.waitForTimeout(150);
  ok(!(await page.$('[data-action="setup.example"]')), 'setup: no example offer over your own data');
  await page.click('[data-action="setup.start"]');
  await page.waitForTimeout(150);
  await page.click('[data-action="setup.skip"]');
  await page.click('[data-action="setup.skip"]');
  await page.waitForTimeout(100);
  await page.fill('#su-checking', '1500');
  await page.click('[data-action="setup.next"]');
  await page.waitForTimeout(100);
  ok(await page.evaluate(() => Store.state.accounts.filter(a => a.kind === 'corriente').map(a => a.balance).join()) === '1500', 'setup: second walk updates the account');
  await page.keyboard.press('Escape');
  await page.waitForTimeout(150);
  // A fresh install opens it by itself, once.
  const fresh = await page.evaluate(() => { Store.reset('empty'); Store.state.settings.welcomeDismissed = false; Setup.maybeOpen(); const a = !!document.querySelector('.modal-backdrop:not(.hidden) [data-action="setup.start"]'); Store.state.settings.setupSeen = true; return a; });
  await page.keyboard.press('Escape');
  await page.waitForTimeout(150);
  ok(fresh && await page.evaluate(() => { const n = document.querySelectorAll('.modal-backdrop:not(.hidden)').length; Setup.maybeOpen(); return n === 0 && document.querySelectorAll('.modal-backdrop:not(.hidden)').length === 0; }), 'setup: opens on a fresh install, not after');
  // Salary schedule confirmation in English.
  await page.evaluate(() => { Store.reset('empty'); App.changed({ structural: true }); App.go('presupuesto/ingresos'); });
  await page.evaluate(() => { UI.run('pay.edit', {}); });
  await page.waitForTimeout(150);
  await page.evaluate(() => { UI.run('pay.save', {}); });
  await page.waitForTimeout(200);
  const payToast = await page.evaluate(() => [...document.querySelectorAll('.toast')].map(t => t.textContent).join('|'));
  ok(/Saved: On the 15th and 30th, every month/.test(payToast) && /On the 15th and 30th/.test(await page.textContent('#pay-summary')), 'pay schedule saved message and summary in English', payToast);
  // PIN lock screen in English.
  await page.evaluate(async () => { await Device.setPin('1234'); Device.lockNow(); });
  await page.waitForTimeout(150);
  const lockTxt = await page.textContent('#lock-screen');
  await page.fill('#lock-pin', '9999');
  await page.click('#lock-screen button[type="submit"]');
  await page.waitForTimeout(400);
  const wrong = await page.textContent('#lock-msg');
  ok(/Type your PIN to get in/.test(lockTxt) && /ZeroDebtPlan/.test(lockTxt) && /Wrong PIN\. 4 tries left/.test(wrong), 'PIN screen and its messages in English', [lockTxt, wrong]);
  await page.fill('#lock-pin', '1234');
  await page.click('#lock-screen button[type="submit"]');
  await page.waitForTimeout(400);
  ok(!(await page.$('#lock-screen')) && await page.evaluate(() => I18n.lang) === 'en' && /Overview|Budget/.test(await page.textContent('#main-nav')), 'unlocking keeps the app in English');
  await page.evaluate(() => Device.removePin());
  ok(errors.length === 0, 'no console errors', errors);
  console.log(`\n${pass} passed, ${fail} failed`);
  await browser.close();
  process.exit(fail ? 1 : 0);
})().catch(e => { console.error(e); process.exit(1); });
